# Generated by Django 6.0.1 on 2026-01-30 11:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HoneypotSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_name", models.CharField(max_length=100, unique=True)),
                (
                    "phone_number",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("terminated", "Terminated"),
                            ("timeout", "Timeout"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("total_calls_received", models.PositiveIntegerField(default=0)),
                ("suspicious_calls_count", models.PositiveIntegerField(default=0)),
                ("configuration", models.JSONField(default=dict)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_honeypots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_honeypots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-start_time"],
                "indexes": [
                    models.Index(
                        fields=["status", "phone_number"],
                        name="honeypot_ho_status_a9abaf_idx",
                    ),
                    models.Index(
                        fields=["created_by", "status"],
                        name="honeypot_ho_created_51f0e2_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ScammerProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("aliases", models.JSONField(default=list)),
                ("scam_types", models.JSONField(default=list)),
                ("risk_score", models.FloatField(default=0.0)),
                ("total_calls_made", models.PositiveIntegerField(default=0)),
                ("successful_scams", models.PositiveIntegerField(default=0)),
                ("reported_count", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("banned", "Banned"),
                            ("under_investigation", "Under Investigation"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                ("location_data", models.JSONField(default=dict)),
                ("associated_numbers", models.JSONField(default=list)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_scammer_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_scammer_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-risk_score", "-last_seen"],
                "indexes": [
                    models.Index(
                        fields=["phone_number", "status"],
                        name="honeypot_sc_phone_n_adb17b_idx",
                    ),
                    models.Index(
                        fields=["risk_score", "status"],
                        name="honeypot_sc_risk_sc_9824c2_idx",
                    ),
                    models.Index(
                        fields=["last_seen"], name="honeypot_sc_last_se_735669_idx"
                    ),
                ],
            },
        ),
    ]
