# Generated by Django 6.0.1 on 2026-01-30 18:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("honeypot", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HoneypotInteraction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("scammer_number", models.CharField(db_index=True, max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("terminated", "Terminated"),
                            ("timeout", "Timeout"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("duration", models.DurationField(blank=True, null=True)),
                ("conversation_transcript", models.JSONField(default=list)),
                ("extracted_information", models.JSONField(default=dict)),
                (
                    "scam_type_identified",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("success_rating", models.FloatField(default=0.0)),
                (
                    "ai_agent_state",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("turn_count", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "honeypot_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to="honeypot.honeypotsession",
                    ),
                ),
                (
                    "scammer_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interactions",
                        to="honeypot.scammerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_time"],
                "indexes": [
                    models.Index(
                        fields=["honeypot_session", "status"],
                        name="honeypot_ho_honeypo_4581a1_idx",
                    ),
                    models.Index(
                        fields=["scammer_number", "start_time"],
                        name="honeypot_ho_scammer_109612_idx",
                    ),
                    models.Index(
                        fields=["status", "start_time"],
                        name="honeypot_ho_status_aed188_idx",
                    ),
                ],
            },
        ),
    ]
