# Generated by Django 6.0.1 on 2026-01-30 11:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CallRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("caller_number", models.CharField(db_index=True, max_length=20)),
                ("recipient_number", models.CharField(db_index=True, max_length=20)),
                ("call_start_time", models.DateTimeField(db_index=True)),
                ("call_end_time", models.DateTimeField(blank=True, null=True)),
                ("duration", models.DurationField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("incoming", "Incoming"),
                            ("outgoing", "Outgoing"),
                            ("missed", "Missed"),
                            ("completed", "Completed"),
                        ],
                        default="incoming",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-call_start_time"],
            },
        ),
        migrations.CreateModel(
            name="AudioUpload",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("audio_file", models.FileField(upload_to="call_recordings/")),
                ("file_size", models.PositiveIntegerField()),
                ("duration", models.DurationField(blank=True, null=True)),
                ("format", models.CharField(max_length=10)),
                ("checksum", models.CharField(max_length=128, unique=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "call_record",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audio",
                        to="calls.callrecord",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.AddIndex(
            model_name="callrecord",
            index=models.Index(
                fields=["caller_number", "call_start_time"],
                name="calls_callr_caller__08d07f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="callrecord",
            index=models.Index(
                fields=["recipient_number", "call_start_time"],
                name="calls_callr_recipie_800b8e_idx",
            ),
        ),
    ]
