# Generated by Django 6.0.1 on 2026-01-30 11:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("analysis", "0001_initial"),
        ("calls", "0001_initial"),
        ("honeypot", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("scam_call", "Scam Call Report"),
                            ("suspicious_activity", "Suspicious Activity"),
                            ("honeypot_interaction", "Honeypot Interaction"),
                            ("investigation", "Investigation Report"),
                            ("follow_up", "Follow-up Report"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("escalated", "Escalated"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("incident_date", models.DateTimeField()),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                ("involved_parties", models.JSONField(default=dict)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("tags", models.JSONField(default=list)),
                ("internal_notes", models.TextField(blank=True, null=True)),
                ("public_summary", models.TextField(blank=True, null=True)),
                ("resolution", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "ai_analysis",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to="analysis.aianalysisresult",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "call_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to="calls.callrecord",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "honeypot_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to="honeypot.honeypotsession",
                    ),
                ),
                (
                    "scam_probability",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to="analysis.scamprobabilityscore",
                    ),
                ),
                (
                    "scammer_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to="honeypot.scammerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EvidenceFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="evidence/")),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("audio", "Audio Recording"),
                            ("transcript", "Transcript"),
                            ("screenshot", "Screenshot"),
                            ("document", "Document"),
                            ("log", "Log File"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("file_size", models.PositiveIntegerField()),
                ("checksum", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_encrypted", models.BooleanField(default=False)),
                (
                    "encryption_key",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_files",
                        to="reports.report",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["status", "priority", "created_at"],
                name="reports_rep_status_3b8594_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["report_type", "status"], name="reports_rep_report__4cebb9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["created_by", "status"], name="reports_rep_created_4bb467_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["assigned_to", "status"], name="reports_rep_assigne_f77543_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="evidencefile",
            unique_together={("report", "checksum")},
        ),
    ]
