# Generated by Django 6.0.1 on 2026-01-30 11:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("calls", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIAnalysisResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "analysis_type",
                    models.CharField(
                        choices=[
                            ("speech_to_text", "Speech to Text"),
                            ("sentiment_analysis", "Sentiment Analysis"),
                            ("keyword_extraction", "Keyword Extraction"),
                            ("scam_detection", "Scam Detection"),
                            ("voice_biometrics", "Voice Biometrics"),
                            ("language_detection", "Language Detection"),
                            ("comprehensive", "Comprehensive Analysis"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("timeout", "Timeout"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("confidence_score", models.FloatField(blank=True, null=True)),
                ("processing_time", models.DurationField(blank=True, null=True)),
                ("results", models.JSONField(default=dict)),
                ("raw_output", models.TextField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "model_version",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("api_used", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "cost",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "audio_upload",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_analysis",
                        to="calls.audioupload",
                    ),
                ),
                (
                    "call_record",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_analysis",
                        to="calls.callrecord",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_analysis_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScamProbabilityScore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("overall_score", models.FloatField()),
                (
                    "scam_level",
                    models.CharField(
                        choices=[
                            ("low", "Low Risk"),
                            ("medium", "Medium Risk"),
                            ("high", "High Risk"),
                            ("critical", "Critical Risk"),
                        ],
                        max_length=10,
                    ),
                ),
                ("factors", models.JSONField(default=dict)),
                ("keywords_matched", models.JSONField(default=list)),
                ("patterns_detected", models.JSONField(default=list)),
                ("voice_analysis_score", models.FloatField(blank=True, null=True)),
                ("text_analysis_score", models.FloatField(blank=True, null=True)),
                ("behavioral_score", models.FloatField(blank=True, null=True)),
                ("historical_score", models.FloatField(blank=True, null=True)),
                ("threshold_used", models.FloatField(default=0.5)),
                (
                    "false_positive_probability",
                    models.FloatField(blank=True, null=True),
                ),
                ("explanation", models.TextField(blank=True, null=True)),
                ("review_notes", models.TextField(blank=True, null=True)),
                ("is_manually_overridden", models.BooleanField(default=False)),
                ("original_score", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ai_analysis",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scam_probability",
                        to="analysis.aianalysisresult",
                    ),
                ),
                (
                    "call_record",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scam_probability",
                        to="calls.callrecord",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scam_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-overall_score", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="aianalysisresult",
            index=models.Index(
                fields=["status", "analysis_type", "created_at"],
                name="analysis_ai_status_192b56_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aianalysisresult",
            index=models.Index(
                fields=["call_record", "status"], name="analysis_ai_call_re_2bbb68_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aianalysisresult",
            index=models.Index(
                fields=["confidence_score"], name="analysis_ai_confide_0f8dd9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scamprobabilityscore",
            index=models.Index(
                fields=["overall_score", "scam_level"],
                name="analysis_sc_overall_20b932_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="scamprobabilityscore",
            index=models.Index(
                fields=["call_record", "overall_score"],
                name="analysis_sc_call_re_bfd10f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="scamprobabilityscore",
            index=models.Index(
                fields=["scam_level", "created_at"],
                name="analysis_sc_scam_le_a0cfdf_idx",
            ),
        ),
    ]
