# Generated by Django 6.0.1 on 2026-01-30 11:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("debug", "Debug"),
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("critical", "Critical"),
                        ],
                        default="info",
                        max_length=10,
                    ),
                ),
                (
                    "component",
                    models.CharField(
                        choices=[
                            ("auth", "Authentication"),
                            ("calls", "Call Processing"),
                            ("analysis", "AI Analysis"),
                            ("storage", "File Storage"),
                            ("api", "API"),
                            ("database", "Database"),
                            ("system", "System"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("details", models.JSONField(default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("hostname", models.CharField(blank=True, max_length=100, null=True)),
                ("process_id", models.PositiveIntegerField(blank=True, null=True)),
                ("thread_id", models.CharField(blank=True, max_length=50, null=True)),
                ("request_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["level", "component", "timestamp"],
                        name="logs_system_level_cf221a_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="logs_system_timesta_1ce06b_idx"
                    ),
                    models.Index(
                        fields=["request_id"], name="logs_system_request_555140_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("view", "View"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("export", "Export"),
                            ("import", "Import"),
                            ("analyze", "Analyze"),
                            ("report", "Report"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("call_record", "Call Record"),
                            ("audio_upload", "Audio Upload"),
                            ("ai_analysis", "AI Analysis"),
                            ("scam_score", "Scam Score"),
                            ("honeypot_session", "Honeypot Session"),
                            ("scammer_profile", "Scammer Profile"),
                            ("report", "Report"),
                            ("evidence_file", "Evidence File"),
                            ("system", "System"),
                        ],
                        max_length=20,
                    ),
                ),
                ("resource_id", models.UUIDField(blank=True, null=True)),
                (
                    "resource_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("session_id", models.CharField(blank=True, max_length=255, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("details", models.JSONField(default=dict)),
                ("old_values", models.JSONField(default=dict)),
                ("new_values", models.JSONField(default=dict)),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("duration", models.DurationField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "timestamp"],
                        name="logs_auditl_user_id_a7304b_idx",
                    ),
                    models.Index(
                        fields=["action", "resource_type", "timestamp"],
                        name="logs_auditl_action_2b9544_idx",
                    ),
                    models.Index(
                        fields=["resource_type", "resource_id"],
                        name="logs_auditl_resourc_52fc75_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="logs_auditl_timesta_630212_idx"
                    ),
                ],
            },
        ),
    ]
