# Generated by Django 6.0.1 on 2026-02-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0002_auditlog_severity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "Create"),
                    ("update", "Update"),
                    ("delete", "Delete"),
                    ("view", "View"),
                    ("login", "Login"),
                    ("logout", "Logout"),
                    ("upload", "Upload"),
                    ("export", "Export"),
                    ("import", "Import"),
                    ("analyze", "Analyze"),
                    ("report", "Report"),
                ],
                max_length=20,
            ),
        ),
    ]
