# Generated by Django 6.0.1 on 2026-01-30 13:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("analysis", "0001_initial"),
        ("calls", "0001_initial"),
        ("reports", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_analysis_complete", models.BooleanField(default=True)),
                ("email_high_risk_alert", models.BooleanField(default=True)),
                ("email_honeypot_engaged", models.BooleanField(default=False)),
                ("email_admin_review", models.BooleanField(default=False)),
                ("email_law_enforcement", models.BooleanField(default=False)),
                ("email_system_alert", models.BooleanField(default=True)),
                ("dashboard_analysis_complete", models.BooleanField(default=True)),
                ("dashboard_high_risk_alert", models.BooleanField(default=True)),
                ("dashboard_honeypot_engaged", models.BooleanField(default=True)),
                ("dashboard_admin_review", models.BooleanField(default=True)),
                ("dashboard_law_enforcement", models.BooleanField(default=False)),
                ("dashboard_system_alert", models.BooleanField(default=True)),
                ("sms_high_risk_alert", models.BooleanField(default=False)),
                ("sms_law_enforcement", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("analysis_complete", "Analysis Complete"),
                            ("high_risk_alert", "High Risk Alert"),
                            ("honeypot_engaged", "Honeypot Engaged"),
                            ("admin_review", "Admin Review Required"),
                            ("law_enforcement", "Law Enforcement Notification"),
                            ("system_alert", "System Alert"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("dashboard", "Dashboard"),
                            ("sms", "SMS"),
                            ("push", "Push Notification"),
                        ],
                        default="dashboard",
                        max_length=10,
                    ),
                ),
                ("data", models.JSONField(default=dict)),
                ("is_read", models.BooleanField(default=False)),
                ("is_sent", models.BooleanField(default=False)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "related_analysis",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="analysis.aianalysisresult",
                    ),
                ),
                (
                    "related_call",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="calls.callrecord",
                    ),
                ),
                (
                    "related_report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="reports.report",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_read", "created_at"],
                        name="notificatio_user_id_8a7c6b_idx",
                    ),
                    models.Index(
                        fields=["notification_type", "created_at"],
                        name="notificatio_notific_f2e0f7_idx",
                    ),
                    models.Index(
                        fields=["priority", "created_at"],
                        name="notificatio_priorit_f7c359_idx",
                    ),
                ],
            },
        ),
    ]
